'use client'
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_component/header"
import Footer from "./_component/footer"
import { ClerkProvider } from "@clerk/nextjs";
import { CardContext } from "./_context/CardContext";
import { useState } from "react";


const inter = Roboto({ subsets: ["latin"], weight: "700" });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [card,setCard] = useState([])
  
  return (
    <ClerkProvider>
      <CardContext.Provider value={{card,setCard}}>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
      </CardContext.Provider>
    </ClerkProvider>
  );
}
